remove unnecessary semicolons

diff --git a/nordvpn-server-find b/nordvpn-server-find
--- a/nordvpn-server-find
+++ b/nordvpn-server-find
@@ -32,8 +32,8 @@ while getopts ":l:c:h" opt; do
     l)
       array_contains iso_codes "$OPTARG"  && location=$OPTARG >&2 || \
         { 
-          echo "Invalid location."; 
-          echo "Please provide a valid, 2-letter ISO 3166-1 code to -l."; 
+          echo "Invalid location."
+          echo "Please provide a valid, 2-letter ISO 3166-1 code to -l."
           echo "(ex: -l us)"; exit 1; 
         }
       ;;
@@ -43,14 +43,14 @@ while getopts ":l:c:h" opt; do
         capacity=$OPTARG >&2; 
       else
         { 
-          echo "Invalid capacity."; 
-          echo "Please provide an integer between 1-100 to -c."; 
+          echo "Invalid capacity."
+          echo "Please provide an integer between 1-100 to -c."
           echo "(ex: -c 90)"; exit 1; 
         }
       fi
       ;;
     :)
-      echo "Option -$OPTARG requires an argument."
+      echo "Option -$OPTARG requires an argument." >&2
       echo "Use -h to show the help." >&2
       exit 1
       ;;
